// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package transfers

import (
	"context"
	"github.com/sptGabriel/banking/app/domain/entities/transfers"
	"github.com/sptGabriel/banking/app/domain/vos"
	"sync"
)

// Ensure, that UseCaseMock does implement UseCase.
// If this is not the case, regenerate this file with moq.
var _ UseCase = &UseCaseMock{}

// UseCaseMock is a mock implementation of UseCase.
//
// 	func TestSomethingThatUsesUseCase(t *testing.T) {
//
// 		// make and configure a mocked UseCase
// 		mockedUseCase := &UseCaseMock{
// 			CreateTransferFunc: func(ctx context.Context, transfer transfers.Transfer) error {
// 				panic("mock out the CreateTransfer method")
// 			},
// 			GetTransfersFunc: func(ctx context.Context, id vos.AccountId) ([]transfers.Transfer, error) {
// 				panic("mock out the GetTransfers method")
// 			},
// 		}
//
// 		// use mockedUseCase in code that requires UseCase
// 		// and then make assertions.
//
// 	}
type UseCaseMock struct {
	// CreateTransferFunc mocks the CreateTransfer method.
	CreateTransferFunc func(ctx context.Context, transfer transfers.Transfer) error

	// GetTransfersFunc mocks the GetTransfers method.
	GetTransfersFunc func(ctx context.Context, id vos.AccountId) ([]transfers.Transfer, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateTransfer holds details about calls to the CreateTransfer method.
		CreateTransfer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Transfer is the transfer argument value.
			Transfer transfers.Transfer
		}
		// GetTransfers holds details about calls to the GetTransfers method.
		GetTransfers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID vos.AccountId
		}
	}
	lockCreateTransfer sync.RWMutex
	lockGetTransfers   sync.RWMutex
}

// CreateTransfer calls CreateTransferFunc.
func (mock *UseCaseMock) CreateTransfer(ctx context.Context, transfer transfers.Transfer) error {
	if mock.CreateTransferFunc == nil {
		panic("UseCaseMock.CreateTransferFunc: method is nil but UseCase.CreateTransfer was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Transfer transfers.Transfer
	}{
		Ctx:      ctx,
		Transfer: transfer,
	}
	mock.lockCreateTransfer.Lock()
	mock.calls.CreateTransfer = append(mock.calls.CreateTransfer, callInfo)
	mock.lockCreateTransfer.Unlock()
	return mock.CreateTransferFunc(ctx, transfer)
}

// CreateTransferCalls gets all the calls that were made to CreateTransfer.
// Check the length with:
//     len(mockedUseCase.CreateTransferCalls())
func (mock *UseCaseMock) CreateTransferCalls() []struct {
	Ctx      context.Context
	Transfer transfers.Transfer
} {
	var calls []struct {
		Ctx      context.Context
		Transfer transfers.Transfer
	}
	mock.lockCreateTransfer.RLock()
	calls = mock.calls.CreateTransfer
	mock.lockCreateTransfer.RUnlock()
	return calls
}

// GetTransfers calls GetTransfersFunc.
func (mock *UseCaseMock) GetTransfers(ctx context.Context, id vos.AccountId) ([]transfers.Transfer, error) {
	if mock.GetTransfersFunc == nil {
		panic("UseCaseMock.GetTransfersFunc: method is nil but UseCase.GetTransfers was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  vos.AccountId
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetTransfers.Lock()
	mock.calls.GetTransfers = append(mock.calls.GetTransfers, callInfo)
	mock.lockGetTransfers.Unlock()
	return mock.GetTransfersFunc(ctx, id)
}

// GetTransfersCalls gets all the calls that were made to GetTransfers.
// Check the length with:
//     len(mockedUseCase.GetTransfersCalls())
func (mock *UseCaseMock) GetTransfersCalls() []struct {
	Ctx context.Context
	ID  vos.AccountId
} {
	var calls []struct {
		Ctx context.Context
		ID  vos.AccountId
	}
	mock.lockGetTransfers.RLock()
	calls = mock.calls.GetTransfers
	mock.lockGetTransfers.RUnlock()
	return calls
}
