// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package accounts

import (
	"context"
	"github.com/sptGabriel/banking/app/domain/vos"
	"sync"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
// 	func TestSomethingThatUsesRepository(t *testing.T) {
//
// 		// make and configure a mocked Repository
// 		mockedRepository := &RepositoryMock{
// 			CreateFunc: func(ctx context.Context, account *Account) error {
// 				panic("mock out the Create method")
// 			},
// 			DoesExistByCPFFunc: func(ctx context.Context, cpf vos.CPF) (bool, error) {
// 				panic("mock out the DoesExistByCPF method")
// 			},
// 			GetAllFunc: func(ctx context.Context) ([]Account, error) {
// 				panic("mock out the GetAll method")
// 			},
// 			GetByCPFFunc: func(ctx context.Context, cpf vos.CPF) (*Account, error) {
// 				panic("mock out the GetByCPF method")
// 			},
// 			GetByIDFunc: func(ctx context.Context, cpf vos.AccountId) (*Account, error) {
// 				panic("mock out the GetByID method")
// 			},
// 			UpdateBalanceFunc: func(ctx context.Context, account *Account) error {
// 				panic("mock out the UpdateBalance method")
// 			},
// 		}
//
// 		// use mockedRepository in code that requires Repository
// 		// and then make assertions.
//
// 	}
type RepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, account *Account) error

	// DoesExistByCPFFunc mocks the DoesExistByCPF method.
	DoesExistByCPFFunc func(ctx context.Context, cpf vos.CPF) (bool, error)

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]Account, error)

	// GetByCPFFunc mocks the GetByCPF method.
	GetByCPFFunc func(ctx context.Context, cpf vos.CPF) (*Account, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, cpf vos.AccountId) (*Account, error)

	// UpdateBalanceFunc mocks the UpdateBalance method.
	UpdateBalanceFunc func(ctx context.Context, account *Account) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account *Account
		}
		// DoesExistByCPF holds details about calls to the DoesExistByCPF method.
		DoesExistByCPF []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cpf is the cpf argument value.
			Cpf vos.CPF
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByCPF holds details about calls to the GetByCPF method.
		GetByCPF []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cpf is the cpf argument value.
			Cpf vos.CPF
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cpf is the cpf argument value.
			Cpf vos.AccountId
		}
		// UpdateBalance holds details about calls to the UpdateBalance method.
		UpdateBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account *Account
		}
	}
	lockCreate         sync.RWMutex
	lockDoesExistByCPF sync.RWMutex
	lockGetAll         sync.RWMutex
	lockGetByCPF       sync.RWMutex
	lockGetByID        sync.RWMutex
	lockUpdateBalance  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *RepositoryMock) Create(ctx context.Context, account *Account) error {
	if mock.CreateFunc == nil {
		panic("RepositoryMock.CreateFunc: method is nil but Repository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account *Account
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, account)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedRepository.CreateCalls())
func (mock *RepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	Account *Account
} {
	var calls []struct {
		Ctx     context.Context
		Account *Account
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DoesExistByCPF calls DoesExistByCPFFunc.
func (mock *RepositoryMock) DoesExistByCPF(ctx context.Context, cpf vos.CPF) (bool, error) {
	if mock.DoesExistByCPFFunc == nil {
		panic("RepositoryMock.DoesExistByCPFFunc: method is nil but Repository.DoesExistByCPF was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cpf vos.CPF
	}{
		Ctx: ctx,
		Cpf: cpf,
	}
	mock.lockDoesExistByCPF.Lock()
	mock.calls.DoesExistByCPF = append(mock.calls.DoesExistByCPF, callInfo)
	mock.lockDoesExistByCPF.Unlock()
	return mock.DoesExistByCPFFunc(ctx, cpf)
}

// DoesExistByCPFCalls gets all the calls that were made to DoesExistByCPF.
// Check the length with:
//     len(mockedRepository.DoesExistByCPFCalls())
func (mock *RepositoryMock) DoesExistByCPFCalls() []struct {
	Ctx context.Context
	Cpf vos.CPF
} {
	var calls []struct {
		Ctx context.Context
		Cpf vos.CPF
	}
	mock.lockDoesExistByCPF.RLock()
	calls = mock.calls.DoesExistByCPF
	mock.lockDoesExistByCPF.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *RepositoryMock) GetAll(ctx context.Context) ([]Account, error) {
	if mock.GetAllFunc == nil {
		panic("RepositoryMock.GetAllFunc: method is nil but Repository.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedRepository.GetAllCalls())
func (mock *RepositoryMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetByCPF calls GetByCPFFunc.
func (mock *RepositoryMock) GetByCPF(ctx context.Context, cpf vos.CPF) (*Account, error) {
	if mock.GetByCPFFunc == nil {
		panic("RepositoryMock.GetByCPFFunc: method is nil but Repository.GetByCPF was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cpf vos.CPF
	}{
		Ctx: ctx,
		Cpf: cpf,
	}
	mock.lockGetByCPF.Lock()
	mock.calls.GetByCPF = append(mock.calls.GetByCPF, callInfo)
	mock.lockGetByCPF.Unlock()
	return mock.GetByCPFFunc(ctx, cpf)
}

// GetByCPFCalls gets all the calls that were made to GetByCPF.
// Check the length with:
//     len(mockedRepository.GetByCPFCalls())
func (mock *RepositoryMock) GetByCPFCalls() []struct {
	Ctx context.Context
	Cpf vos.CPF
} {
	var calls []struct {
		Ctx context.Context
		Cpf vos.CPF
	}
	mock.lockGetByCPF.RLock()
	calls = mock.calls.GetByCPF
	mock.lockGetByCPF.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *RepositoryMock) GetByID(ctx context.Context, cpf vos.AccountId) (*Account, error) {
	if mock.GetByIDFunc == nil {
		panic("RepositoryMock.GetByIDFunc: method is nil but Repository.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cpf vos.AccountId
	}{
		Ctx: ctx,
		Cpf: cpf,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, cpf)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//     len(mockedRepository.GetByIDCalls())
func (mock *RepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	Cpf vos.AccountId
} {
	var calls []struct {
		Ctx context.Context
		Cpf vos.AccountId
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// UpdateBalance calls UpdateBalanceFunc.
func (mock *RepositoryMock) UpdateBalance(ctx context.Context, account *Account) error {
	if mock.UpdateBalanceFunc == nil {
		panic("RepositoryMock.UpdateBalanceFunc: method is nil but Repository.UpdateBalance was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account *Account
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockUpdateBalance.Lock()
	mock.calls.UpdateBalance = append(mock.calls.UpdateBalance, callInfo)
	mock.lockUpdateBalance.Unlock()
	return mock.UpdateBalanceFunc(ctx, account)
}

// UpdateBalanceCalls gets all the calls that were made to UpdateBalance.
// Check the length with:
//     len(mockedRepository.UpdateBalanceCalls())
func (mock *RepositoryMock) UpdateBalanceCalls() []struct {
	Ctx     context.Context
	Account *Account
} {
	var calls []struct {
		Ctx     context.Context
		Account *Account
	}
	mock.lockUpdateBalance.RLock()
	calls = mock.calls.UpdateBalance
	mock.lockUpdateBalance.RUnlock()
	return calls
}
